version: '3'
services:
  db:
    image: "postgres:11.2-alpine"
    container_name: spring-boot-angular-db
    volumes:
      - ../dbsetup/src/main/resources/db/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ../dbsetup/src/main/resources/db/data.sql:/docker-entrypoint-initdb.d/02_data.sql
    restart: always
    networks:
      - mynetwork
networks:
  mynetwork: {}
